services:
  webapp:
    build: ./pr3_tradecompany_aspnet_mvc
    ports:
      - "8000:80"
    environment:
      - ConnectionStrings__TradeCompany=Server=db;Port=5432;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB} 
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pr3_tradecompany_aspnet_mvc/db:/docker-entrypoint-initdb.d  
volumes:
  postgres_data: